---
name: Template-Plugin-AudioFile-Info
version: 1.03
author:
  - 'Dave Cross, E<lt>dave@dave.org.ukE<gt>'
abstract: |-
  Template Toolkit plugin for
  AudioFile::Info
license: perl
requires:
  AudioFile::Info: 0
  Template: 0
  perl: 5.6.0
provides:
  Template::Plugin::AudioFile::Info:
    file: lib/Template/Plugin/AudioFile/Info.pm
    version: 1.03
generated_by: Module::Build version 0.261
